### ISSUE TITLE
REQUEST: change handling of sitemap if file open

### ISSUE THREAD

**Issue by azithinkiam** [azithinkiam/brsgis_plugin#19]
[site map print.zip](https://github.com/azithinkiam/brsgis_plugin/files/4657959/site.map.print.zip)

**Comment by azithinkiam** [comment]
unable to reproduce - pending additional information from NWP.

**Comment by Cadmanick** [comment]
Autocad locks files which uses as reference images.  site.jpg is a referenced file in the root directory of my standard template dwg file.  so opening any new dwg in any folder with a site.jpg locks the site.jpg. 
 If you were to open a cad file on .25, then try to create a sitemap, you would get the error.  this is helpful when tweaking the sitemap to display the correct lot or portion thereof.  This will become increasingly useful once we have a working job move tool.

**Comment by azithinkiam** [comment]
apparently, the xref demand-load setting (2) should prevent this and only load a copy of the xref, leaving the original to be modified.  apparently, that is not the case with civil3D19 as i confirmed that setting is as it should be and yet the file remains locked.  modified code as requested.  validated on .25/NWP/PRD/19-425.  site-1.jpg created as expected.

resolved (v2.7)
