### ISSUE TITLE
(PENDING) | (NWP) | REQUEST: update/validate moveJob & moveSupplemental utilities

### ISSUE THREAD

**Issue by azithinkiam** [azithinkiam/brsgis_plugin#22]

**Comment by azithinkiam** [comment]
functions are mostly complete and working as expected.  need to account for new attributes introduced with line/freehand and supplemental objects.  supp_type for sure, likely others.  fields() an option for merging?

**Comment by azithinkiam** [comment]
need to update both classes to use the new updateAttribute() function, reduce non-value code waste.

**Comment by azithinkiam** [comment]
per NWP: "The first candidate is to move job 18-383 from adjacent parcels to roadline of Atlantic Ave. adjacent..."

not enough information provided.  need to know destination parcel(s) to move feature.

**Comment by Cadmanick** [comment]
This move (18-383) looks perfect, exactly as requested.  Now i have a list a mile long that i want to assign to Caren.  Is the tool ready for primetime?

**Comment by azithinkiam** [comment]
Not even a little bit.  I have to move them manually for now.  If you don’t want me to just blast through that list and are dead set on Caren handling them, it’s gonna be a few days.

**Comment by Cadmanick** [comment]
Could you have it in a few weeks?  Please!

**Comment by azithinkiam** [comment]
it won't take anywhere near a few weeks.  i just needed a couple days to shift primary focus to trying to make sense of what's really happening to us.  i think i'm mostly there and returning to "normal" today.

**Comment by Cadmanick** [comment]
Can we move this back to the top of the priority list?

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/87249829-6d087800-c42f-11ea-994e-d796bb3216a9.png)

move JOB utility updated and validated in DEV on .25 with 18-325.  job was moved from existing merged feature to 006 027 003 and back, contact moved with job as expected.

NOTE: the original (source) job is NOT deleted by this tool.  this is by design.  upon successful move and verification, source parcel must be manually deleted to avoid duplicates.

please test and advise.

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/87251029-cb852480-c436-11ea-801f-9091ebd41075.png)

move SUPPLEMENTAL utility updated and validated in DEV in MY ENVIRONMENT with K-0655.  supp was moved from existing feature to both single and multiple parcel local features as expected.  

NOTE: the original (source) supp is NOT deleted by this tool.  this is by design.  upon successful move and verification, source feature must be manually deleted to avoid duplicates. 

IMPORTANT: this is not yet available in .25 as i need to change the CRS for the existing features to make this work properly.  if you notice a move appears to complete successfully but the feature is NOT visible on the map, something wen't wrong.  this is the behavior that requires the CRS change.

-t.

**Comment by azithinkiam** [comment]
move SUPPLEMENTAL utility updated and validated in DEV on .25 with K-0692. supp was moved from existing feature to both single and multiple parcel local features as expected.

please test and advise.

**Comment by Cadmanick** [comment]
Any chance move la_plan could be easily added to this tool?

**Comment by azithinkiam** [comment]
Nope – that would need to be a new tool…completely different tables/layers/etc.

**Comment by Cadmanick** [comment]
Can you make this happen.  this is the first place i need to start with moving things around.

**Comment by Cadmanick** [comment]
I don't have any actual jobs and supplementals to move but while just moving things around to see how it all works i notice that we cannot change object type, i.e. cannot move parcel to line or freehand and vice-versa.  this will be necessary for many plans, as they are incorrectly associated with a parcel and need to be associated with a line, or freehand.  is this possible?

**Comment by Cadmanick** [comment]
ok found a k to move 3164 from map 4-64 to 4-69-C & A.
1. it crashed after selecting the parcel with.:
![image](https://user-images.githubusercontent.com/1892068/88403505-a67ba480-cd9a-11ea-92c5-fca042a21073.png)
pressing ok yeilds:
![image](https://user-images.githubusercontent.com/1892068/88403553-b72c1a80-cd9a-11ea-891b-b670f446a76a.png)
then get to this:
![image](https://user-images.githubusercontent.com/1892068/88403662-d3c85280-cd9a-11ea-9bce-18fb586c0f4f.png)
pressing "ok" gets:
![image](https://user-images.githubusercontent.com/1892068/88403729-e5115f00-cd9a-11ea-8942-b987147c9347.png)
then merge goes as planned:
![image](https://user-images.githubusercontent.com/1892068/88403776-f65a6b80-cd9a-11ea-9bc3-485158aa9906.png)
then this after pressing "ok"
![image](https://user-images.githubusercontent.com/1892068/88403809-01ad9700-cd9b-11ea-9704-aeaaa7642cf0.png)
with the grand finale of 👍 
![image](https://user-images.githubusercontent.com/1892068/88403843-11c57680-cd9b-11ea-86af-7707f10f2d04.png)
which is correct but... but seemed like something was getting murdered in the process!!!

**Comment by Cadmanick** [comment]
Here is another one, that doesn't seem to work..  try to move K-189.  it belongs on the peninsula south of it's current location near map15 lots 24-35.
1. i cannot seem to select it for use with the tool.

**Comment by azithinkiam** [comment]
You can move anything you want in DEV – you don’t need to “find” an actual job that needs to be moved…it’s a testing environment.

 

In every case, if you get an exception, something is wrong and you need to stop.  Nothing that happened after the first exception is relevant.

 

The exception provides the error and the location of the error – this is all I need to troubleshoot.  If you screen capture the exception message, that’s sufficient.

 

I’ll have to jump on that machine to see exactly what line of code that is…but the same move works fine for me, so I’m not sure what you’re doing that’s breaking it.  Par for the course.


I’ll be back tomorrow night.

 

-t.

**Comment by azithinkiam** [comment]
RE: we cannot change object type, i.e. cannot move parcel to line or freehand and vice-versa. this will be necessary for many plans, as they are incorrectly associated with a parcel and need to be associated with a line, or freehand. is this possible?
-
anything is possible, but it's not easy and would require completely redoing these yet again.  you have me spending a LOT of time trying to code things that would be so much easier if you just had someone who was comfortable in QGIS do the work.  i really wish you would put some thought into how it could make sense for you to just have me do this stuff manually rather than spending weeks trying to come up with a programmatic approach.  it would take me MAYBE 5 minutes to "move" a job or supp from whatever to whatever...if i could just do it rather than trying to script a way to have someone who doesn't really understand what they're doing do it.

if this is the level of programming you're asking for, i think i need to push back.  it's just not worth the time or effort to piecemeal solutions to your data problems that really have nothing to do with the program itself.  if the functionality is there from the beginning, there would never be a need to perform this task.  so you're asking me to develop a solution to a problem that i can fix a different and better and easier and cheaper (for you) way.  

you don't need a full-time developer...you need a full-time QGIS person and you don't have that.  i've offered many times and i'm offering again.  we need to figure out a better way to use me...this isn't working.

**Comment by azithinkiam** [comment]
RE: K-189

this is related to the comment above.  there is no parcel where you're trying to move this, so there's nowhere to move it to.  is there no parcel associated with this plan?  if not, then you'd need to either 1) create a new parcel or 2) create a freehand job/supp.  again, it would be much quicker to just create the thing correctly and then change the number after-the-fact.  that could be done in minutes as opposed to weeks if not longer developing something smart enough to realize there is no feature available to move the thing to...and then prompting you to either create the parcel or the new job.

i can't stress this enough - most of this stuff is best addressed manually, not through more plugin code.

**Comment by azithinkiam** [comment]
i've moved K-3164 back and forth several times on .DEV without any issues.  your machine/environment must have been in a broken state when you got these errors.  i can find no problems with the code.  will move to PRD as-is and address additional concerns separately.  i do not want to do more new development on "MOVE" tools when everything is better/easier fixed manually.

**Comment by azithinkiam** [comment]
how many of your 1000+ "move" cases have been identified thus far?  i'm still going back and forth on this...

my concern is that even if i make something work for the 3 or 4 scenarios you've mentioned so far, it won't be everything you need to do in these 1000+ cases...leading to more development as you find things it doesn't do.  i'm still pretty sure i'd rather address these manually...even if there are 2000 cases.  it's just night and day easier than trying to code this.

**Comment by Cadmanick** [comment]
There are 9 variants.

3 job types * 3 feature types.  

i just cannot train you from afar to do this work.  i rely on someone here in the office that can work independently, with a 30 minute session, max, per day for questions from previous day or immediate issues...  someone here in my office needs to pull the plan, look on the tax map, find the lot and move the object... i have only identified less than 300.  it's just that i expect that this number will grow multi-fold, like feedback in a speaker.  i imagine from what i've experienced so far that the problem is much deeper than i've yet seen.   

so, no I don't need this program... i just really want it for the future ambitions i have for this software.  if you cannot do it, then lets just go the other way.  if you can, i'd prefer to try.  this tool in a polished state will be useful for many more people than me and my company.  that's the main reason i want to do it programmaticaly...

if you can code for 9 variants then we should be all set!

NWP

**Comment by azithinkiam** [comment]
updated and implemented in PRD - will revisit non-parcel job types at a later time
