### ISSUE TITLE
Job - abutter and related work

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#24]
1. map_table has been making current job an abutter
2. map_table has been making current job related_work to current job.
See attached pdf for details, 
Z:\0 - Settings\Equipment\GIS\BRS_db\issues\20-219_MapTable_2020.05.20-abutters-job.pdf

[20-219_MapTable_2020.05.20-abutters-job.pdf](https://github.com/azithinkiam/brsgis_plugin/files/4684214/20-219_MapTable_2020.05.20-abutters-job.pdf)

**Comment by azithinkiam** [comment]
1. resolved in previous update.

2. confirmed, WIP...

**Comment by azithinkiam** [comment]
2. resolved in v2.6 update, confirmed on .27/Office/Office/PRD: 

![image](https://user-images.githubusercontent.com/39959187/83078772-53aa9880-a048-11ea-9adc-26d80157b034.png)
