### ISSUE TITLE
(PENDING) REQUEST: Solution to selecting feature to edit - overlapping Job, Supp & plans

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#25]
Per email from 5-26-20 attached please create funtionality to ask to "select parcel" or "use existing selected feature" when starting the edit command on all of Job, Supps & La_Plans.
Where many jobs, supps or plans overlap.
[RE  selecting job with other jobs on parcel.pdf](https://github.com/azithinkiam/brsgis_plugin/files/4684581/RE.selecting.job.with.other.jobs.on.parcel.pdf)

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/83200764-0eeb3400-a112-11ea-8561-a816b777ce86.png) > 

if a selection exists: 
![image](https://user-images.githubusercontent.com/39959187/83200806-22969a80-a112-11ea-87dd-ee77fc451ec1.png)

if continue: 
![image](https://user-images.githubusercontent.com/39959187/83200834-3215e380-a112-11ea-8eff-333f91d0621e.png)

edit process from that point is not altered.

if new selection:
![image](https://user-images.githubusercontent.com/39959187/83201176-f0396d00-a112-11ea-82f8-3113118e3d12.png)

edit process from that point is not altered.

if NO SELECTION, edit process is not altered.

does that meet your needs?  if so, i can proceed with applying this framework to jobs/supps...currently only done for la_plans.

**Comment by Cadmanick** [comment]
That should work.

**Comment by azithinkiam** [comment]
implemented in v2.8, moved to PRD.
