### ISSUE TITLE
(PENDING) k-supp number null on new job creation on office

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#26]
Ater searching for parcel in Newcastle on map, 4 lot 64 Office PC gets this: 
![search error](https://user-images.githubusercontent.com/1892068/83024292-2cc67500-9ffc-11ea-9237-8f8088475a3e.png)

creating a new supplemental K on this lot yeilds this:
![supp-job created no number assigned](https://user-images.githubusercontent.com/1892068/83024189-fee13080-9ffb-11ea-8a1a-89f5273f09b5.png)
this si very similar to what was happening on 5-26-20 when trying to create a new supp.

**Comment by azithinkiam** [comment]
unable to reproduce search issue.  unable to reproduce NULL supp_no issue on latest update (v2.6).  can confirm i was able to create a K on this parcel without issue and it is available for editing via the standard process:  

![image](https://user-images.githubusercontent.com/39959187/83080492-57401e80-a04c-11ea-89cc-9b350dcd237d.png)

resolved.
