### ISSUE TITLE
(PENDING) job 20-222 irrelevant abutters

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#27]
[20-222_MapTable_2020.05.26.xlsx](https://github.com/azithinkiam/brsgis_plugin/files/4689019/20-222_MapTable_2020.05.26.xlsx)

None of the abutters on maps 19, 15 are relevant.

**Comment by azithinkiam** [comment]
WIP...

**Comment by azithinkiam** [comment]
unable to reproduce.  creating a job on this parcel works as expected in my environment and abutters appear correct:

[20-233_MapTable_2020.05.27.xlsx](https://github.com/azithinkiam/brsgis_plugin/files/4689241/20-233_MapTable_2020.05.27.xlsx)

was this also created on office?  it's starting to look like they're not using the correct plugin, but i can't verify without getting on the machine.

please advise when i can RDP.

PENDING.

**Comment by Cadmanick** [comment]
...they use the plugin that you set them up on.  RDP is available in this machine until next Tuesday (6-2-2020).

**Comment by azithinkiam** [comment]
confirmed issue on OFFICE pc.  purged all abutters for this job from DB, manually re-generated and confirmed output was as expected:

![image](https://user-images.githubusercontent.com/39959187/83079740-7b026500-a04a-11ea-8282-bb44ff6aeb8c.png)

NOTE: the first time i attempted to re-generate abutters for this job on this machine, QGIS appeared to lock up, but not error out - perpetual hourglass.  after endtask/relaunch, no issues whatsoever and abutter generation completed in ~6s.  starting to suspect a potential issue unique to this PC...possibly hardware, possibly user profile.  issue is resolved, but similar issues may persist if there is something uniquely off about this particular machine.  code is good.

**Comment by Cadmanick** [comment]
this user "office" on this pc ".27" is the only setup without administrator access.  Ann is no longer with us so i can remove this.
