### ISSUE TITLE
(PENDING) | (NWP) | REQUEST: MapView / YellowSheet field updates

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#34]
1. Please change the name listed on the MapView sheets to Folder Name, not Client name.  Also,
please make this change for the contacts page.   
2. Name at top should be Folder name and not Client name.
3. Also on the yellow sheet, can you add some logic to the Client name field?  If client name is not = to contact 1 then add client name to field B4 and make field B5 = Contact 1 (as shown on the attached- styling same as shown except for yellow hi-liting).  The alt-styling is not as big of a deal if that is too difficult to quickly do (though it would be nice for easy visual file differentiation).

[20-199_YellowSheet_2020.04.30.xlsx](https://github.com/azithinkiam/brsgis_plugin/files/4723480/20-199_YellowSheet_2020.04.30.xlsx)

**Comment by Cadmanick** [comment]
Related... this needs repair.  modify to folder label display name as marked-up in:
[20-199_MapTable_2020.06.04.xlsx](https://github.com/azithinkiam/brsgis_plugin/files/4730570/20-199_MapTable_2020.06.04.xlsx)

**Comment by azithinkiam** [comment]
WIP...

**Comment by azithinkiam** [comment]
requested changes have been made and are available for testing in DEV on .25 with the exception of the contacts page.  since the purpose of that document is to list all contacts for a job, you're going to get both the client and folder contacts if they're not the same.  given that they're all going to be present in the output, i'm not sure what change you're actually requesting for this one.  please test and advise.

-t.

**Comment by Cadmanick** [comment]
"3. Also on the yellow sheet, can you add some logic to the Client name field? If client name is not = to contact 1 then add client name to field B4 and make field B5 = Contact 1 (as shown on the attached- styling same as shown except for yellow hi-liting). The alt-styling is not as big of a deal if that is too difficult to quickly do (though it would be nice for easy visual file differentiation)."

did you add this into the mix?  

test on job number 20-254 attached.

[Copy of 20-254_YellowSheet_2020.07.10.xlsx](https://github.com/azithinkiam/brsgis_plugin/files/4948837/Copy.of.20-254_YellowSheet_2020.07.10.xlsx)
[20-254_YellowSheet_2020.07.10.xlsx](https://github.com/azithinkiam/brsgis_plugin/files/4948838/20-254_YellowSheet_2020.07.10.xlsx)


The yellow area is the area of interest (do not color yellow)  this is just showing the requested results of the logic i hope you can implement.

nwP

**Comment by azithinkiam** [comment]
Did you not test this?  I just generated another one on my end and it’s working as you requested: 

 



 

I don’t have the latest copy of your DB so I can’t do 20-254 yet…pulling a copy now.

 

-t.

**Comment by Cadmanick** [comment]
ok,  we're getting close... 
1. do not mark yellow. i was simply marking yellow to bring your attention to the issue!
2. place "primary contact" in client name.
3. make this field (primary contact) styling identical to this
see = Z:\BRS\2020\20-199\Job_Info...   or see below \/
[20-199_YellowSheet_2020.04.30.xlsx](https://github.com/azithinkiam/brsgis_plugin/files/4974150/20-199_YellowSheet_2020.04.30.xlsx)

**Comment by azithinkiam** [comment]
DEV has been updated per request.  please test and advise.

**Comment by Cadmanick** [comment]
Dev is getting close.
1. Change MapView Title to "Folder Name"  (i.e. in example 20-199 should be "Grimmel Family Trust" and not "Knickerbocker")
2. Change MapTable Cell A1:C2 to "Folder Name"  (i.e. in example 20-199 should be "Grimmel Family Trust" and not "Knickerbocker")
3. Change MapTable Cell E6 to "Folder Name"  (i.e. in example 20-199 should be "Grimmel Family Trust" and not "Knickerbocker")


Additional:
4. While we're here, using the similar logic (when client != folder_name), can we add to cell A3 on the FolderFacelabel.xlsx the phrase "c/o: " client_name?  in much less bold letters and right justified?

Thanks!

**Comment by azithinkiam** [comment]
1 – 3 have been completed in DEV.

 

I’ll see what I can do on #4.

**Comment by azithinkiam** [comment]
RE: 4 – 

 

Like this?


Grimmel Family Trust


(Owner)


c/o:


	

20 FACTORY COVE ROAD


BOOTHBAY HARBOR

	
	

Map 5, Lot 20

	

SDP

	

Job #:


20-199

	

drawn by:__________ date:___________ scale: __________

	

Due:

 

If not, please provide an example.

**Comment by azithinkiam** [comment]
Better pic:

**Comment by Cadmanick** [comment]
you left no pic attached...  like this.
![image](https://user-images.githubusercontent.com/1892068/88695418-db0b9b00-d0cf-11ea-85a4-af2e276fbef9.png)

**Comment by azithinkiam** [comment]
updated in PRD, validated with NWP/20-199.  closing.

**Comment by Cadmanick** [comment]
ok this is not right.... please assist ASAP  we're printing incorrect folders.  

The "c/o ..." is only to be placed on the folder face label if the client is not the owner!
not every folder as you have it now.

"Additional:
4. While we're here, using the similar logic **(when client != folder_name), can we add to cell A3 on the FolderFacelabel.xlsx** the phrase "c/o: " client_name? in much less bold letters and right justified?
"

does that make sense?

**Comment by azithinkiam** [comment]
at no point previously did you mention anything about owner...only folder name and client name, neither of which have a value of 'owner'.  i think you mean to use folder_type somewhere as that's what the owner will be set on.  so, once again, please provide the exact logic you wish to use...i can only work off the information you're giving me.  i think you're confusing yourself with the different column names.

folder_name = the name to display on the folder (contact with folder_checked) - "Grimmel Family Trust"
folder_type = the contact type of the folder_name contact - "Owner"
client_name = the client name (contact with client checked) - "Knickerbocker"
client_role = the contact type of the client_name contact - "Site Contractor"
primary_contact = the primary contact for the folder_name "Rachael Bathgate"

so i need to know the logic to follow potentially using all of these fields.  currently, this is all that prints on the folder face:

            ws['A1'] = folderName
            ws['A2'] = '(' + folderType + ')'
            if str(folderName) != str(clientName):
                ws['A3'] = 'c/o: ' + clientName
            else:
                ws['A3'] = ''
            ws['A6'] = addr
            ws['A7'] = town.upper()
            ws['A10'] = map_bk_lot
            ws['A12'] = jobType + jobSubType
            ws['A15'] = jobNo
            if str(date_due) == '1900-01-01':
                ws['A20'] = ''
            else:
                ws['A20'] = date_due

currently, we're showing the folder_type in A2 regardless of what the value is...in this case, it is 'owner.'

what isn't how you want it?

-t.

**Comment by Cadmanick** [comment]
![image](https://user-images.githubusercontent.com/1892068/89649233-6afad300-d88e-11ea-877a-2087f0a961f7.png)
in the attached image above field A3 has the owner's name in it.  this is not the intended design.  i only want this field populated if the owner is not the client.  can you help me with the necessary logic to get to this end.  i don't want to trouble shoot your code.

also, i thought we were placing the owner last name in cell(A1) with the owner first names in Cell(A2)  this seems to have changed.
i.e.
![image](https://user-images.githubusercontent.com/1892068/89649611-12780580-d88f-11ea-9a90-97f0ca6c87ec.png)


please,
nwp

**Comment by azithinkiam** [comment]
It changed a long time ago when you had me add folder name.  We display it exactly as entered in the contact name field for the folder contact, as decided by you eons ago when that went in.


I’m not asking you to troubleshoot a damn thing.  I’m asking you to provide me with the information I need to do the work.   Until you can do that, there’s nothing for me to do.

**Comment by azithinkiam** [comment]
This is how 20-270 generates for me…exactly as expected.

 



 

This is how 20-293 generates for me…exactly as expected.

 

--

 

Until you can find me one that isn’t as you expect, there is nothing for me to do.

**Comment by Cadmanick** [comment]
please note that there are no images when you post a reply.

this is when you started adding the eroneous "(owner)"... 11 days ago
![image](https://user-images.githubusercontent.com/1892068/89664850-bff61380-d8a5-11ea-8d17-5fda151bc5b7.png)

**Comment by Cadmanick** [comment]
20-245, 18-174 & 20-250 are all correct.  i want the owner of the property, last name bold in A1, the first names below and if the owner of the property is not the client, then i want cell A3 to be "who to send the bill to".
does that make sense.  i don't know how to break it down further.

**Comment by azithinkiam** [comment]
we haven't used first and last name in well over a year.  submit a new request with wtfever it is you think you want now and i'll work on it when i can.  i'm sick of this back and forth bullshit.

**Comment by azithinkiam** [comment]
That is the folder type and has been included since last year when you had me change from first/last name to foldername…it wasn’t just added.  You really need to start paying more attention to your own shit.  I’m getting really sick of this.

**Comment by Cadmanick** [comment]
so could you please change it to  conform with my standards?  my standards are as previously stated...
"i want the owner of the property, last name bold in A1, the first names below and if the owner of the property is not the client, then i want cell A3 to be "who to send the bill to""

i guess my ladies are changing it back to my standardized way after your program outputs the wrong thing.. i dunno i will ask them on Monday.

**Comment by azithinkiam** [comment]
I’m not changing anything until you can talk to your people and figure out what you really need.  We’ve already completely redone the way these are printed once…and everything was “fine” until you introduced the c/o change last week.

 

AGAIN, “owner” isn’t a thing…that’s just a value coming from the contact type of the folder contact and being stored as “folder type” and shown as “client role” on the form.  

 

I think the logic is fine and exactly as you requested…it sure looks like it in the tests that I do.  Apparently, if I send an image through e-mail response, that doesn’t end up in GH…I’ll do those updates manually in GH from now on.

 

LMK after you figure out what they’re doing…and what you really need.

**Comment by Cadmanick** [comment]
please update the FolderFaceLabel as follows:

A1 = left of comma of "Folder Label Display Name" - "Contact name", if coma exists include the comma at the end.  should appear like "surname,"
A2 = right of comma of "Folder Label Display Name" or "Primary Contact" if no coma existed above.  should appear like "proper name" (or "Primary Contact" if it is a company).
A3 = should only contain the "Client" - "Contact Name" if the "Folder Label Display Name" is not the "CLIENT".

NWP

**Comment by azithinkiam** [comment]
Are you ABSOLUTELY SURE this is what you want?

 

There is once again no mention of “owner” whatsoever…so hopefully you can see why this is so damn confusing for me.  You keep going back and forth and this is almost exactly how it was originally configured.

 

Apparently the “c/o” is gone now, too?

 

PLEASE CONFIRM before I start coding this.

**Comment by Cadmanick** [comment]
dont' just blindly code, please...

The subtle difference is the requested logic.  the reason we did that interim fix of labeling the folder type, was to determine when the client was not the folder name.  and the requestsed logic above bridges that gap.

do you understand what im asking for and why?  if so i approve to move to production if not. please call me so i can hear your concerns.

thank you,

Nicholas

**Comment by Cadmanick** [comment]
"Apparently the “c/o” is gone now, too?"

this is not true... only when the client is not the folder label..  do you understand?

**Comment by azithinkiam** [comment]
THAT’S HOW IT IS NOW.

**Comment by azithinkiam** [comment]
I don’t.  

 

The problem with trying to change back to looking for a comma is the other data you have in there:

 

Grimmel Family Trust

Susan & Bill Smith


We decided it was best to use “Folder Display Name” as a 1:1 field where you entered it exactly as you wanted to display on the label…what’s the problem with that now?

 

I can work with you to figure out the handling of owner vs. not, but you need to understand where that value comes into play and when it can be used.  I think it’s currently configured the way you want.

 

I do NOT want to try to go back to parsing out first name and last name…it’s a PITA unless your folks can always enter things in a standard format so I know how to address the oddballs.  I don’t think that’s possible, so I think we end back up where we started…in that it’s currently the best solution.

 

Please test and let me know what IS NOT CORRECT with how they generate today.

**Comment by Cadmanick** [comment]
this is exactly why i requested that you store first and last name separately... you said let me handle it, but here we are.

Could you correct it to place the "primary contact" in cell 'a2' instead of "folder type"... 
AIR, i think my request with "folder type" was intended to be as a concatenation of "primary contact" + "folder type"

**Comment by azithinkiam** [comment]
We haven’t EVER stored First/Last separately and it doesn’t matter what your intention was when it’s been like it is and just fine for a year.  

 

If you want changes, you need to think them through, figure out what you want and I’ll try to determine what the potential “gotchas” are. 

 

I’m sitting here ready to do SOMETHING for you and you still can’t just sit down and figure out what it is that you want.

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/90542869-c82a3a80-e152-11ea-8bab-0c4a8047b2af.png)
