### ISSUE TITLE
(PENDING) | (DONE) | ISSUE: No old K-'s (that i've seen) have date, surveyor, or notes included from access db

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#35]
Examples supps are k-564 & k-530...  neither of these previous K's contain the data from the old access db.  can you fix this?  these two fields should map to "requested date", "surveyor" and "notes".  This short list is a minimum of useful data from the old access db.  Other useful columns may exist and should be map able to this new db.

See image linked here for what should be in access db.

![KsMissingSurvDate+Notes](https://user-images.githubusercontent.com/1892068/86271703-60686200-bb9b-11ea-83a1-2ed73262de76.jpg)

**Comment by Cadmanick** [comment]
for Supps, date should be "recorded date", for most.  i erroneously said it should be "requested date", it should not.
we are missing "locus address" = address, "client name" = name & "job type" = job
for La_plans "date" should be "date requested"...

**Comment by azithinkiam** [comment]
reviewing - this may be related to those fields not existing by that specific name in the brs_jobs table.  if confirmed, it's a quick/easy fix.

**Comment by azithinkiam** [comment]
this should now be resolved in PRD.  all fields were updated manually in the database.  issue was due to the different column names between the two tables.  only fields that matched exactly were included as attributes via copy/paste process.  my apologies for the oversight.  please advise/confirm.

**Comment by Cadmanick** [comment]
In doing this fix, i notice that supplementals "date requested" values are the same as "date recorded" field values.  These were intended to be two separate fields.  For supplementals the date from access should be the recording date.  For plans this imported data from access should be "date requested", which you have on the la_plans feature attribute custom form titled "date of plan:".  I assume this is a carryover from the access stuff, but the difference is very big... so i would prefer only these two fields available in the two tables (supps&la_plans) with the data sorted in each way (outlined in comment 2 above) please...

**Comment by azithinkiam** [comment]
ok, so both plans and  K-supps started as la_plans, so those only had a single date value available which is 'date' in access and displayed as 'date of plan' in QGIS.  new supplementals have both date requested and date recorded as available fields, so given that we only had a single date input value, i set them both to that.  we can tweak however you'd like, but i'm not sure where a different date value will come from...

so it sounds like 'date of plan' is going to be used as 'date recorded' for K-supps and left alone for la_plans...but you also have the date_requested field - what goes there?  again, there's only the single date value in a plan record (see attached).

![image](https://user-images.githubusercontent.com/39959187/86911135-c9466180-c0e8-11ea-8de8-fe81c01dd184.png)

**Comment by Cadmanick** [comment]
1. For la_plans the imported "date" data from the access db should be "date requested".

2. For Supps, the imported "date" data from the access db should be "recorded date".

These differences are very important, these date fields should be moved respectively to each new field.  

3. Supps does not reference 'date of plan'.   The 'date of plan' as shown above on the "la_plans feature attribute" custom form, should be "date requested".

4. The 'Date Recorded' as shown at lower right on the "brs_supplementals feature attribute" custom form, should be "recorded date".  The other date shown on this form at middle top, is "date requested" and should be null, blank or 1/1/1901, since it didn't have a suitable import source.

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/87248121-9e7c4600-c425-11ea-8c74-f5401b054930.png)

is this what you want la_plans to look like?  this just has the label that previously read "date of plan" renamed to "date requested."  if so, i'll approach the other form like this.  if not, let's jump on a quick call and talk through changes in real-time.

-t.

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/87248189-13e81680-c426-11ea-9487-693bad187baf.png)

is this what you want brs_supplementals to look like?  i changed bottom right to 'recorded date' but i'm still not sure what you want date requested to be or if you want it at all.  it sounds like you want it hidden / not used.  please advise.  

-t.

**Comment by azithinkiam** [comment]
"Date Requested" set to NULL for all K plans not created in 2020.
"Date Recorded" label changed to "Recorded Date"
"Recorded Date" set to 'date' value from Access DB for all K plans not created in 2020.

this should complete the request.  please verify and confirm.

**Comment by Cadmanick** [comment]
looks good.  close
