### ISSUE TITLE
(PENDING) | (UnableToReproduce) | ISSUE: enforce feature attribute custom form to autosize to a useful size in supps & la_plans & jobs

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#36]
feature attribute form often upon first use in a session, and sometimes (depending on machine) for all sessions, default to unusable size, approximately 80x200pixels.  can you get this to default to something more useful, like the minimum size to see all the data in the dialog box?

**Comment by azithinkiam** [comment]
WIP...

**Comment by azithinkiam** [comment]
unable to reproduce with 'default' profile.  verified code forces form size.  please advise which user/machine/qgs file can reproduce this issue.  pending.

**Comment by Cadmanick** [comment]
nicholas on .75 has the error, though i have not been able to save the .qgs file in weeks...  so that is why it will not persist, i assume.

**Comment by azithinkiam** [comment]
please let me know when i can get on .75 to check.

**Comment by Cadmanick** [comment]
.75 will be on all weekend, unless we lose power due to tropical storm headed our way!  It still happens every time i open custom forms...

**Comment by azithinkiam** [comment]
just tried again on .75 (logged in as Nicholas) and this is what i get: 

jobs:
![image](https://user-images.githubusercontent.com/39959187/87212127-ed719080-c2ea-11ea-92aa-a96714fae66a.png)

plans:
![image](https://user-images.githubusercontent.com/39959187/87212146-011cf700-c2eb-11ea-851d-d84593b91c94.png)

supps:
![image](https://user-images.githubusercontent.com/39959187/87212156-1003a980-c2eb-11ea-9e36-29a749aef116.png)

i cannot reproduce this behavior.  please send me a full screenshot the next time you make this happen.

-t.

**Comment by Cadmanick** [comment]
![image](https://user-images.githubusercontent.com/1892068/87432944-b6370400-c5b6-11ea-94b9-631fa813e859.png)
this just happend on .25 in dev....

**Comment by azithinkiam** [comment]
it didn't "just happen" as you had to have attempted some action prior to the form launching...did you just try to identify a plan?  edit a plan?  create a plan?  as per usual, need more information...attempting to reproduce again.

**Comment by azithinkiam** [comment]
identify plan #4-0154 produces this:  
![image](https://user-images.githubusercontent.com/39959187/87476992-56ac1900-c5f5-11ea-898a-d51a0bfb3c4c.png)

**Comment by azithinkiam** [comment]
edit plan #4-0154 produces this: 
![image](https://user-images.githubusercontent.com/39959187/87477184-b4406580-c5f5-11ea-8aad-2421497a3e8a.png)

once again, i am not able to reproduce the behavior you are seeing.  you will need to provide exact step-by-step instructions to reproduce this before i can troubleshoot further.  just as with .75, .25/DEV is working as expected.

-t.

**Comment by Cadmanick** [comment]
While selecting 4-1784 from "identify feature" on .75 i get.  Once i set the width it reopens fine until reboot.
![image](https://user-images.githubusercontent.com/1892068/88081168-016c8c00-cb4e-11ea-8eb6-abd42c8db315.png)

**Comment by azithinkiam** [comment]
OK, then I’ll need to get on .75 and reboot before I can troubleshoot further.  This is hard-set in the code that launches the form, so there’s really no way it should be happening.  LMK when I can do this.

**Comment by Cadmanick** [comment]
4:20 (everyday) is when i leave.

**Comment by azithinkiam** [comment]
this is resolved.  i changed the way the form opens and it now will always force width and suggest height.

**Comment by Cadmanick** [comment]
went to verify f's on .25 and get this... is it RDP that does it with all of these orphaned modals?
![image](https://user-images.githubusercontent.com/1892068/88684242-a34a2680-d0c2-11ea-8a6f-b711585d0cb4.png)

**Comment by azithinkiam** [comment]
Seems to be – just get out of QGIS and they’ll go away.

**Comment by Cadmanick** [comment]
mainly voicing the non expanidng subject modal box here...

**Comment by Cadmanick** [comment]
on .75 went to edit supps, selected k-1939 and got this.
![image](https://user-images.githubusercontent.com/1892068/90025368-fd7ee600-dc83-11ea-9061-12e3f0a56660.png)

**Comment by azithinkiam** [comment]
There’s something really weird going on with that machine.  It’s apparently opening everything as my ID (LEIGHTON\tim.schmaltz) and not your account…

 

I don’t know if that’s what’s going on with this particular issue or not, but again I need to get on your machine right after a reboot to troubleshoot.

 

Can I jump on that box around your lunchtime today?  I’m off today and tomorrow and can dig into a lot of this stuff if you’ll be available to help.
