### ISSUE TITLE
(PENDING) | (NWP) | REQUEST: serve image layers on server as layer

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#37]
Z:\GEO DATA\geolib_6in_2013\tifs\Boothbay Area\2013_xxxxxxxxx.tif

or possibly move them to a more universal location to load more using the same scheme.... i.e. per year, per resolution, per type...

no rush just a need down the road.

**Comment by azithinkiam** [comment]
assigned.

**Comment by azithinkiam** [comment]
request is vague / unclear.  please explain what you mean to do with these .tif files.  i'd think you could add them as raster layers as they are...and being on Z:\ they're already on the server.  i just don't understand what you're looking for on this one.

**Comment by Cadmanick** [comment]
the state's servers have gotten 200% faster we will put this on the back burner for a future revision.
