### ISSUE TITLE
(PENDING) | (NWP) | REQUEST: tool to create la_plan on a lot

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#38]
We've found 3 this week.  la_plans that are not in the db.  Will your move tool account for items that don't exists yet, in this case?

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/87247919-a5568900-c424-11ea-903f-085b7c515043.png)

new plan tool validated in DEV.  2-9999 was created using this feature.  please test in your DEV environment on .25 and advise.

-t.

**Comment by Cadmanick** [comment]
perfect please implement in prd.
