### ISSUE TITLE
(PENDING) | (NWP) | ISSUE: screen resolution and dialog boxes

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#40]
office-2 is operating at 1600x900 and cannot see the "OK" and "cancel" buttons.
see attached image.
![image](https://user-images.githubusercontent.com/1892068/87570306-6d567c80-c696-11ea-99fa-3528196b4a8d.png)

We need to always be able to see these buttons.  please revise to ensure this.

**Comment by azithinkiam** [comment]
Sounds like you need to upgrade to a better monitor that can support the required resolution.

**Comment by Cadmanick** [comment]
The desk space cannot fit a larger monitor, it's the desk at the front door with weird cubby's and her eyes cannot see the higher rez.  (caren is 70+) and you do not like me to use scaling and/or it doesn't work.  Are there any other options here?  should M$ scaling work?

**Comment by azithinkiam** [comment]
I don’t think scaling will work but feel free to try it.  I don’t know what you expect me to do about this…the only real option is to make the form smaller but that’ll affect every user and every form…and I still don’t know if it would be able to fit all the fields without a redesign.  What’s she been doing for the past 3 years?

**Comment by azithinkiam** [comment]
try auto-hide the taskbar in desktop mode; that might give her just enough more screen to make it fit.  as you can see, there isn't much room available to play with...i'm not sure i can squeeze everything on a smaller form without changing the size of the fields and that could cause other issues.  you can also resize and move...so what i'd personally do is:

shorten the form just a bit by using the top bar: 
![image](https://user-images.githubusercontent.com/39959187/88388830-4299b180-cd83-11ea-8ecf-e1e097479f62.png)
  
once it's shorter, you can move it up the screen and click OK.

**Comment by azithinkiam** [comment]
actually, the supp form is much smaller so it shouldn't be an issue.  is this only a problem with brs_jobs for her?

**Comment by azithinkiam** [comment]
is this still an issue?
