### ISSUE TITLE
(PENDING) | (NWP) | REQUEST: new supplemental type "F"

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#41]
F

I need to track old folders form Robert Schmidtman (ME PLS 67) that we're finding in droves...   it's easiest if we can just make a new type called "F".  and as we find un-indexed folders in the back room, we will index them with an "F-"

**Comment by Cadmanick** [comment]
This one is high priority, if possible.

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/88388222-15003880-cd82-11ea-81d8-dc68919bf34b.png)

i need to know what specific values / fields you want to be available for this type.  please provide a reference (make like type D, etc.) or markup on the pic above showing what should remain and what it should be called, as well as what should be hidden.

**Comment by Cadmanick** [comment]
make it the same as k's

**Comment by Cadmanick** [comment]
can you implement in DEV?

**Comment by azithinkiam** [comment]
Can do tonight – just need to make several DB / layer / filter changes…code is already there.

**Comment by azithinkiam** [comment]
DONE in DEV.

**Comment by Cadmanick** [comment]
feature looks good approved to move to prod. and close.

**Comment by azithinkiam** [comment]
moved to PRD, tested OK.

**Comment by Cadmanick** [comment]
could you please move 'F' job type above "other" in list, 

thank you!

**Comment by azithinkiam** [comment]
In this form?

**Comment by Cadmanick** [comment]
The invisible form?

**Comment by azithinkiam** [comment]
Not sure what you’re on about…if the attachments aren’t coming through to GH, just fucking say that.
