### ISSUE TITLE
(PENDING) | (EOB FRIDAY) | REQUEST: reformatted layers

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#42]
please see 
![image](https://user-images.githubusercontent.com/1892068/88081288-295bef80-cb4e-11ea-9af9-99b25221efe0.png)
for updates to the layer list and styling.  for usability updates, to all machines.
mostly modified as below;
![image](https://user-images.githubusercontent.com/1892068/88081415-58726100-cb4e-11ea-8f0a-f8b5b9e449bb.png)

**Comment by azithinkiam** [comment]
I need to know what all you’ve changed.  If only the names under the CONUS_wet_poly layer, we only need to replace the other QGS files with a saved version of yours.  If you’ve changed other layers, I’ll have to update the saved QML files as well.

 

Please clarify what has been modified.

**Comment by Cadmanick** [comment]
changed NHDLine to catagorized symbology:
![image](https://user-images.githubusercontent.com/1892068/88090656-e3a62380-cb5b-11ea-909f-f7722af1a47d.png)
conus_wet_poly as shown above.

BBH-zoning map prelimiary as below:
![image](https://user-images.githubusercontent.com/1892068/88090844-2c5ddc80-cb5c-11ea-9287-bd583003b6ad.png)

imagery layers changed weeks ago with the state's moving to new servers, i'm unsure of if they are the same as what you have...
![image](https://user-images.githubusercontent.com/1892068/88090970-60390200-cb5c-11ea-9ee0-a9434d66d82a.png)

i think that's it..

**Comment by Cadmanick** [comment]
I would prefer an update of all .qgs files from my -NWP styles.  i'm changing the size of the labels for supp and plans for more effective plotting on map view.  example being 20-271 not displaying many labels.

**Comment by azithinkiam** [comment]
Let me know when you’re done.  I’ll need to do this after-hours.

**Comment by azithinkiam** [comment]
files were updated over the weekend.  closing.
