### ISSUE TITLE
REQUEST: remove padded 0 in La_plan #'s

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#44]
REQUEST: remove padded zeros in la_plan numbers

**Comment by azithinkiam** [comment]
Probably nothing, but why not just strip them out via expression rather than mess with the data.

**Comment by Cadmanick** [comment]
Because I didn't want them there to begin with.

**Comment by azithinkiam** [comment]
God forbid you implement ANY actual standards.

**Comment by azithinkiam** [comment]
done in dev and prd.
