### ISSUE TITLE
(PENDING) | (NWP) | ISSUE: map table is not picking up k's 

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#47]
is it by any intention for supplementals to not be included in the map table?  can we add K's to the included items in the map table.  in the future i want to include M's and others.  thoughts?

**Comment by azithinkiam** [comment]
Not intentional.  Unintended consequence of splitting out supps.  I have a few ideas on how to address this.

**Comment by azithinkiam** [comment]
try it now.

**Comment by azithinkiam** [comment]
mapTable code updated to ensure supplementals are included.
