### ISSUE TITLE
profiles

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#48]
i need a separate profile for plan_room.  

please.

**Comment by azithinkiam** [comment]
OK – it has it’s own profile now.

 

You might want to move this thing from wireless to wired if you can – should speed it up a bit.

**Comment by Cadmanick** [comment]
Can you check through all pc's after hours tonight or over the weekend to fix the users qgs shortcut files.  They all seem to be broken, saying the file is missing.  Also i edited what i thought was a separate profile for the Plan_room to auto authenticate, and now everyone or many are attempting to do the same can you please throw questions to me and/or resolve?

**Comment by Cadmanick** [comment]
plan room has icons at the bottom of the page no others.. mine .75 is defaulting to icons at the bottom of the page... what's up?

**Comment by azithinkiam** [comment]
No idea – let me jump on your machine.

**Comment by Cadmanick** [comment]
ok check your email.

**Comment by azithinkiam** [comment]
profile / file created.
