### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#49]
**crash shown below is initiated by starting new plan creation (4-429) on map 14 lot 029 in BBH on .75**

![image](https://user-images.githubusercontent.com/1892068/90805158-43255980-e2e9-11ea-9f8d-e331f12dab74.png)
KeyError: 'lat_lon' 
Traceback (most recent call last):
  File "Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/python/plugins\brsgis_plugin\brsgis_dialogs.py", line 376, in select_changed
    lat_lon = jobNo['lat_lon']
KeyError: 'lat_lon'

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.2.3-Bonn Bonn, 9b176802e5 
Python Path:
•	C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python
•	Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/python
•	Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/python/plugins
•	C:/PROGRA~1/QGIS3~1.2/apps/qgis/./python/plugins
•	C:\Program Files\QGIS 3.2\bin\python36.zip
•	C:\PROGRA~1\QGIS3~1.2\apps\Python36\DLLs
•	C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib
•	C:\Program Files\QGIS 3.2\bin
•	C:\PROGRA~1\QGIS3~1.2\apps\Python36
•	C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages
•	C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\win32
•	C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\win32\lib
•	C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\Pythonwin
•	Z:\0 - Settings\GIS\QGIS\plugins\profiles\default/python
•	Z:\0 - Settings\GIS\QGIS\plugins\profiles\default\python\plugins\brsgis_plugin/forms
•	Z:\0 - Settings\GIS\QGIS\plugins\profiles\default\python\plugins\brsgis_plugin/QML
Z:/0 - Settings/GIS/QGIS
![image](https://user-images.githubusercontent.com/1892068/90805211-546e6600-e2e9-11ea-92f0-f96962f0643d.png)

**Comment by azithinkiam** [comment]
Try it again

**Comment by azithinkiam** [comment]
removed filter from plans layer, issue resolved.
