### ISSUE TITLE
Office staff seem to be deleting jobs after creation

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#52]
20-322 got deleted.
she has no idea how she did it.
is there any way to stop this?

is it possible that it is a glitch that is deleting things and not her?

**Comment by Cadmanick** [comment]
we have a full folder and need to recreate the job on that number.
there seem to be alot of empty numbers in the db table...

thoughts, besides the obvious need for training.

**Comment by azithinkiam** [comment]
i'm sure i can get the job back, but doubt there's any way to determine how it was deleted...there is no auditing system built into this and we don't track actions on that level.  will look into number gaps - suppose it COULD be related but without knowing how the job got deleted it's pretty hard to tell.

**Comment by azithinkiam** [comment]
other thoughts: the only way a new job would ever be deleted by code is if there was an issue during creation that generated an exception or error...then rollback.  i'll look through all code and flag any potential deletion events.

**Comment by Cadmanick** [comment]
322 & 324 are deleted unintentional, 323 is likely the one intended to have been deleted, but others were victim to some negligence.

can you recreate 322 324 in db?  both have full digital documents and printed folders...

is this something i can do?  will it mess with the pid#'s or will there be any other consequences if i, in the future try to add it back in myself in the attribute table editor?

**Comment by Cadmanick** [comment]
we have 8 new jobs to process today so time is of the essence...  we are getting up to 3 new jobs a day with no end in sight!  it's crazy here!

**Comment by azithinkiam** [comment]
nothing you can do...this isn't something we've planned for and i'm not sure what the best way to get them back will be yet.  just pulled your db...

**Comment by azithinkiam** [comment]
322/324 restored from backup, new backup taken.  monitoring...

**Comment by Cadmanick** [comment]
333-336 seem to have gone missing as well.  thoughts?

**Comment by azithinkiam** [comment]
they're not missing, but they're not visible likely because they have no job_type set.  this indicates some error or exception during job creation but it's impossible to tell exactly what.  here's what i see in the database:  
![image](https://user-images.githubusercontent.com/39959187/92000849-ff304c80-ed0b-11ea-9d76-3dcf48eea2fd.png)
--
this looks like a repeated attempt to create a job on 003-004 and likely isn't supposed to be 4 unique jobs on that lot...but there's no way for me to know.  

if you can tell me what the correct lot and job_type for these 4 jobs should be, i can update it and they should show up.  however, i think there may be another issue here because they probably shouldn't all be the same lot.

**Comment by azithinkiam** [comment]
NOTE: this is different than yesterday - 322/324 were definitely not present in the DB at all.

**Comment by Cadmanick** [comment]
Ok,  can you delete 20-333,-20-336.  
also please expand 20-331 to include all abutting 34-13 lots to the east as well as the 32-54 to the northwest.

**Comment by azithinkiam** [comment]
i can't do that on 20-331.  better to just delete and re-create that one if it needs to be multiple lots...they definitely borked something putting that in as a single.  apparently, they're getting way more errors and/or exceptions than they're telling you about and just blasting on through things.  to confirm, do you just want 333 and 336 deleted or was that supposed to be 333 through 336 (all 4 jobs)?  if you've already made a folder for 331 and need to keep that number, that's fine...just create it as a new job and let me know the number...then i can change it to 331 and reset the count so you don't lose whatever number it gives you...

**Comment by Cadmanick** [comment]
can you do that?  delete 333, 334, 335, & 336.  also can you create a new job with junk creds and delete and replace as described above?  i'm still running 3.14 on my machine.  need to revert, but my new layers are here with aerial imagery...

**Comment by azithinkiam** [comment]
yes on 333,4,5,6 - no problem there.

for 331 i'm saying just have them recreate the job from scratch as whatever it gives you - 340/1,etc...

once that's done, just let me know what the new number is and i'll change it back to 331 and delete the junk 331.  make sense?

**Comment by Cadmanick** [comment]
i cannot do that.. can you?

**Comment by azithinkiam** [comment]
sorry, just assumed you'd have whoever did it the first time put it back in.  i think it should look like this, yes?

![image](https://user-images.githubusercontent.com/39959187/92007833-6a7e1c80-ed14-11ea-8620-9e5563adc51f.png)

**Comment by Cadmanick** [comment]
now delete 20-331 and renumber we will fix the rest.

**Comment by Cadmanick** [comment]
is there no way to copy the contents from one job to another?

**Comment by azithinkiam** [comment]
actually, i just ended up using the moveJob utility and it worked perfectly: 

![image](https://user-images.githubusercontent.com/39959187/92008355-1162b880-ed15-11ea-9bf8-4349e6d13027.png)

**Comment by Cadmanick** [comment]
hell... ok i thought it was broken.. sorry.

**Comment by Cadmanick** [comment]
i do need to transferr my settings from 3.14 to my old v2.5.....   i switched back so i'll be consistent with others.  once we get the imagery pyramids added i want to change plan room back also, i think.

**Comment by azithinkiam** [comment]
nope, it works fine...but can only handle parcel > parcel(s) moves right now...and i guess line/freehand to parcel would also work...but i have not yet coded the other branches for other feature types - tabled for now per previous discussions.

if there's nothing more to do with these jobs, let's close this out and open a new request for saving your downgrades to 3.2.3 on both your machine and planRoom...when you're ready.

**Comment by Cadmanick** [comment]
ok.  one more... job 20-346 the error happened when she selected a single parcel instead of a double.   i moved the job and now cannot select the other job to delete.  can you help?

don't we want to delete the old item after a successful move command?

**Comment by Cadmanick** [comment]
nm i did it... but i would never want to teach the ladies how to do that!  and they screw up way too much for me to fix all errors for them.. can we look into the delet after successful move option?

**Comment by azithinkiam** [comment]
I strongly advise against automatic deletion of anything without implementing auditing of some kind.  We have to know what gets deleted so we can bring it back when it wasn’t what they wanted to delete.  

 

Realistically, you want “the ladies” doing as little as possible in QGIS and you want a QGIS power user who can do the more complex stuff and/or more destructive actions like moves/deletes…someone like me lol.  

 

Honestly, I think your best case scenario would be to have them get comfortable identifying issues and what needs to happen to correct them…like your post-it-notes…then turning those over to you or me or someone else to just do the needful.  Even if I have to completely create a job and all outputs from scratch, I can do it in about 10m start-to-finish…it’s almost always going to be more efficient to just do whatever’s needed vs. trying to code out every potential scenario, test, rework, etc.

**Comment by azithinkiam** [comment]
resolved.
