### ISSUE TITLE
supplemental creation

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#53]
![image](https://user-images.githubusercontent.com/1892068/91881964-4eb14280-ec50-11ea-896c-840aa0d95f93.png)

this is on lot r01 66-e in boothbay

the supp_number doesn't seem to fill like it used to, and the data stamp is an odd format.  is this something that has changed, is this a side effect of half changing to 3.14?  thoughts

**Comment by azithinkiam** [comment]
no, this was a result of the restored jobs from this morning.  i had to re-enable the triggers that handle ID/job/supp_no creation.  my apologies.
