### ISSUE TITLE
Job move command seems to have deleted client data

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#55]
Using move command on .75 on 20-379, there appears to be now client data in the form.  linda has already output the data to the folder, so it must have been there previously.  any thoughts on why this would happen?

**Comment by azithinkiam** [comment]
Something didn’t work.  I just fixed move stuff over the weekend, but hadn’t moved it to PRD yet as I was hoping you’d test in DEV.  It’s updated now…did the contact move with it?

**Comment by azithinkiam** [comment]
I only see one 20-379 and it looks like it has good data.

**Comment by azithinkiam** [comment]
resolved
