### ISSUE TITLE
mapview creation

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#56]
Map view creation is not using aerial imagery.  Likely due to flaky imagery.  what options do we have?

**Comment by Cadmanick** [comment]
and now i cannot get it to output anything at all...

**Comment by azithinkiam** [comment]
Job number?

**Comment by Cadmanick** [comment]
ok false alarm, linda had the pdf open and it finished as if nothing was wrong except no output was written.. that would be a nice addition.

**Comment by Cadmanick** [comment]
20-386 & 20-387  i think shes zoomed in too far and images are not triggering...

**Comment by Cadmanick** [comment]
ok, confirmed.. it does not load raster below threshold... can you enforce minimum zoom level to combat this limitation with state data?

**Comment by Cadmanick** [comment]
please study, determine threshold scale, and implement minimum print scale enforcement, by zooming out to that scale then print to pdf.

**Comment by azithinkiam** [comment]
Did imagery EVER print on mapView or only SiteMap?  I’ve looked through the code and can’t see where those images are turned off…even after implementing a delay to ensure they’re on screen before generating the PDF, they still don’t show up…even at a known good scale.

 

Looking into this, just want to confirm that you do have some mapViews with imagery from previous jobs…before these latest state issues.

**Comment by azithinkiam** [comment]
No matter what I do, I can’t get imagery to print out on mapView.  I haven’t been able to find any copies that actually have it, so I’m not sure if it was ever there before…but either way, if you need it, I’ll probably have to redo the way that works.

 

LMK when you can.

 

-t.

**Comment by Cadmanick** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by azithinkiam** [comment]
duplicate.
