### ISSUE TITLE
map view

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#57]
no longer getting aerial imagery on mapviews.

**Comment by azithinkiam** [comment]
Did you not see my previous message about this?  I’ve NEVER had imagery on mapViews and there’s nothing in code to prevent it…so I just assumed it wasn’t present at the zoom level we’ve been using.

 

Are you saying that you have, in the past, received imagery on mapView?  If so, that was never explicitly intended…but may have been a nice side effect of the way it was coded. 

 

Unfortunately, if you want imagery on mapView, I think it’s going to need to be completely rebuilt.  No matter what I do, I can’t get it to show up with things as they are currently.

**Comment by azithinkiam** [comment]
Yeah, I just have to completely re-do it once I figure out how to make that layer stay visible…I have absolutely no idea what/why it changed.  In all of my testing I always had it off, but there’s nothing preventing it from showing up.

 

I’m working on it – just haven’t had much time with Jess gone and covering all shifts.

**Comment by Cadmanick** [comment]
we typically print map tables with imagery, fema, parcels and road names showing, check old 2020 jobs...   

if they are not consistent i can give you a list of what i would like for a minimum standards list.

**Comment by Cadmanick** [comment]
works fine for us today...

**Comment by azithinkiam** [comment]
That tells me that random state issues have a direct impact on our ability to generate mapView – do you agree?  

 

There’s supposed to be a way to cache WMS layers…if we can figure that out, it might render all these little oddities moot.

**Comment by azithinkiam** [comment]
seems to be fixed - likely due to state issues.
