### ISSUE TITLE
option to print landscape mapview

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#58]
jobs similar to 20-343 would be better printed in landscape.  any options to make this happen?

**Comment by Cadmanick** [comment]
oops it kinda works weird dialog messages.  wonky but works.

**Comment by azithinkiam** [comment]
You haven’t done one of these in a while, have you? 😉

 

If you have a suggestion on how to make it less wonky, just lemme know.

**Comment by azithinkiam** [comment]
how's this? 

![image](https://user-images.githubusercontent.com/39959187/96265131-10b77600-0f93-11eb-84d7-9813ecdae78e.png)

**Comment by Cadmanick** [comment]
Can you default to portrait? That will work for 90% but sometimes landscape is better…   Sent from Mail for Windows 10 From: azithinkiamSent: Friday, October 16, 2020 9:36 AMTo: azithinkiam/brsgis_pluginCc: Cadmanick; AuthorSubject: Re: [azithinkiam/brsgis_plugin] option to print landscape mapview (#58) how's this?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by azithinkiam** [comment]
That’s how it was set up originally…it would default to Portrait, tell you it’s going to print in portrait and then you have the option to change to Landscape.  

Sounds like you want to revert to that with slightly different prompts?

**Comment by Cadmanick** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by azithinkiam** [comment]
how's this?  

![image](https://user-images.githubusercontent.com/39959187/96478921-40ba7f80-1206-11eb-8d8f-1a6c501dc40c.png)

ENTER/space do the same as clicking YES, so that would be 'defaulting' to portrait.

**Comment by Cadmanick** [comment]
why can this not be used with the default option being portrait... please help me make this simple for the user...

![image](https://user-images.githubusercontent.com/1892068/96611717-f4854300-12ca-11eb-80e8-74b02320d064.png)

**Comment by azithinkiam** [comment]
my bad - misunderstood what you were trying to say.  it can and i'll change it back to that...

**Comment by azithinkiam** [comment]
updated per request
