### ISSUE TITLE
need to create I-157

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#61]
caren's machine crashed when trying to create the subject plan.  i don't think that it would have worked anyhow.  since we havent' discussed pr's and I's previously.  they exist and i will need to be able to handle them.  so can you create this one and assist with creating a tool to create them?

it belongs on Whitefield map 8.... lots 19 & 20.

**Comment by Cadmanick** [comment]
also, the file file is attached for pertinent information... 
[I-157.pdf](https://github.com/azithinkiam/brsgis_plugin/files/5409884/I-157.pdf)

**Comment by azithinkiam** [comment]
So these new types are PLANS not SUPPLEMENTALS?  There’s no reason she shouldn’t be able to create a new plan now, but I can’t really confirm until after I can get on her machine after 4.

**Comment by azithinkiam** [comment]
![image](https://user-images.githubusercontent.com/39959187/96622324-cce8a780-12d7-11eb-8005-1d71ac64ce85.png)

does this look correct?

**Comment by Cadmanick** [comment]
that looks good.  thanks.. they are plans terry had 1,2,4,8, I and PR for his plans prefixes.  I was for Irregular, and PR was for preliminary.

**Comment by azithinkiam** [comment]
created per request - will need to update plan specific details: name, address, etc.
