### ISSUE TITLE
imagery in map view

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#63]
ok possible fix for orthoimagery in map view.

search for file name of coordinates of job centroid corelated to 2018-SPC coverage box here:
![image](https://user-images.githubusercontent.com/1892068/96721391-1093ed80-137a-11eb-8db0-fa9fefd4a882.png)

i.e. use this layer as background imagery for the coverage area in gray shown here:
![image](https://user-images.githubusercontent.com/1892068/96721510-39b47e00-137a-11eb-99a0-7fde66fdc840.png)

i really need aerial imagery in  map views it is super helpful in discussing jobs for estimates...

**Comment by Cadmanick** [comment]
wait,  why are they working on my machine and not linda's ... grrrrrr... brb  i may need to retrane her

**Comment by Cadmanick** [comment]
ok, update.  linda had deleted her 2018 aerial imagery layer. :-(  grrrrr... i re added and now it works great.  we do need to lock down the qgs file for her.  not for me... please... what can we do?

**Comment by azithinkiam** [comment]
Is the OFFICE file fixed (correct) and saved now?  If so, I can make it read-only which will prevent saving over…I can’t do anything about her deleting layers…but if she does, they’ll be restored when she closes and reopens.

**Comment by Cadmanick** [comment]
yes it is saved.

**Comment by azithinkiam** [comment]
And it is now read-only

**Comment by azithinkiam** [comment]
issue was temporary and likely caused by state issues.  if imagery is enabled in the project, it will now display on mapView
