### ISSUE TITLE
map view zoom

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#64]
example job 20-413

when selecting new mapview creation, it seems to zoom in to a useless extents and then save it zoomed way in.  can you fix this i thought our logic was to zoom out to the extents of the job bounds plus a percentage...?  help?

**Comment by azithinkiam** [comment]
This should be resolved – reload the plugin or close/reopen QGIS.  I reverted to the previous code…apparently I borked it up when trying to fix the ortho issue that wasn’t an issue.

**Comment by Cadmanick** [comment]
did this change happen today... she tried it this morning with me lookin over her shoulder... and it failed...

**Comment by azithinkiam** [comment]
Yeah, but not until around 11am.

**Comment by azithinkiam** [comment]
mapView zoom code restored to original
