### ISSUE TITLE
plan creation

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#65]
when starting new plan creation it pre populates the fields with an old job, thoughts on this?

also can i just create an I-xxx here  and a PR-xxx here?  will it disturb anything down stream?

**Comment by azithinkiam** [comment]
DO NOT DO THIS.

 

If it’s pulling anything in from another job, there’s something wrong.  It should only come up with a blank form for new plans…which machine was this on?

**Comment by azithinkiam** [comment]
I’ll look at it tonight – please make sure to leave the PCs on

**Comment by azithinkiam** [comment]
.75 was off last night, so I couldn’t check it…but had no issue creating a new plan on .25 – it came up blank just like it should.  

 

LMK when I can check your machine.  I created that I-157 plan on there, too…so I know it was working. 

 

-t.

**Comment by azithinkiam** [comment]
plan creation is working as expected.  all known issues have been resolved.
