### ISSUE TITLE
Remove "Easement" as job type

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#66]
Route survey should be used instead.

**Comment by azithinkiam** [comment]
Are you asking to just have the Easement option removed from the drop-downs or do you want actual job / supp data changed?

**Comment by Cadmanick** [comment]
remove from dropdown so she cannot choose that type, there is no layer style for easement so it's effectively invisible... that being said, yes if you could change all jobs that are currently easements to route survey that would be fab...

**Comment by azithinkiam** [comment]
removed 'Easement' from job_type for brs_jobs and brs_supplementals.  manually updated 13 jobs from 'Easement' to 'Route Survey' per request.
