### ISSUE TITLE
"misc" layer tree is left expanded after a print map screen command

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#67]
see below
![image](https://user-images.githubusercontent.com/1892068/98836913-4aec2a00-2410-11eb-94c4-50618fe81599.png)

**Comment by Cadmanick** [comment]
this on .75

**Comment by azithinkiam** [comment]
Unable to reproduce – will need to get on .75 after hours.  Please ensure machine is left online.

**Comment by azithinkiam** [comment]
What do you mean by “print map screen?”  I can’t reproduce when generating mapVIew or SiteMap.  I’ve done it both on my end and on .25 with no issue.

**Comment by Cadmanick** [comment]
Also this function "print map view" turns S_fld_haz_Ar & S_fld_haz_Ar VE off.  unwanted.

**Comment by azithinkiam** [comment]
commented disable of type specific layers so they will not be turned off assuming they're on.  could not reproduce 'misc' group issue - suspect another action besides mapView caused this.  please advise if/when it comes back.
