### ISSUE TITLE
FEMA LAYERS ARE TURNED OFF BY SOME PROCESS IN BRS_GIS

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#69]
SEE BELOW
![image](https://user-images.githubusercontent.com/1892068/98950163-a7118580-24c6-11eb-93d4-dfcffd698300.png)

**Comment by azithinkiam** [comment]
i changed this yesterday so those layers would no longer be turned off during siteMap generation.  they're turned ON for MIS, regardless of previous status...but they are NOT turned off by any code in the plugin.  please try to reproduce and advise on exact steps as this should no longer be possible:

        # disable all type-specific layers:
        self.toggleLayer('HAT_2015', 0)
        self.toggleLayer('75ft_SB_HAT_2015', 0)
        # self.toggleLayer('S_Fld_Haz_Ar', 0)
        # self.toggleLayer('S_Fld_Haz_Ar VE', 0)

**Comment by azithinkiam** [comment]
issue is resolved
