### ISSUE TITLE
supplemental creation - ask to select new selection

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#72]
This command does not work as it seems to indicate.  When selecting the button marked "select new" (or something similar, was earlier this week don't remember the exact middle button between ok and cancel...),  I would think it should allow me to make a new selection.  it does not it just quits...

**Comment by azithinkiam** [comment]
'select again' code updated, see line 1284:

elif msg.clickedButton() is again:
